"""
Chief Architect Agent

The master planner that takes a novel premise and generates:
- High-level outline (acts, chapters)
- Character profiles
- World-building rules
- Theme and style guide
"""

from typing import List, Optional
from pydantic import BaseModel, Field

from app.agents.base import BaseAgent
from app.config import settings


class CharacterProfile(BaseModel):
    """A character profile generated by the Architect."""
    name: str = Field(description="Character's full name")
    role: str = Field(description="Role in the story: protagonist, antagonist, supporting, etc.")
    age: Optional[int] = Field(default=None, description="Character's age")
    occupation: Optional[str] = Field(default=None, description="Job or role in society")
    appearance: str = Field(description="Physical description")
    personality: str = Field(description="Key personality traits and quirks")
    backstory: str = Field(description="Brief background and history")
    motivation: str = Field(description="What drives this character")
    arc: str = Field(description="How this character changes throughout the story")
    relationships: List[str] = Field(default_factory=list, description="Key relationships with other characters")


class ChapterOutline(BaseModel):
    """A single chapter in the outline."""
    number: int = Field(description="Chapter number (1-indexed)")
    title: str = Field(description="Chapter title")
    summary: str = Field(description="What happens in this chapter (200-300 words)")
    pov_character: str = Field(description="Point of view character for this chapter")
    location: str = Field(description="Primary setting/location")
    key_events: List[str] = Field(description="3-5 key events or beats")
    emotional_arc: str = Field(description="The emotional journey of this chapter")


class WorldRule(BaseModel):
    """A world-building rule or fact."""
    category: str = Field(description="Category: magic, technology, society, geography, etc.")
    name: str = Field(description="Name of the concept")
    description: str = Field(description="Detailed explanation")
    constraints: List[str] = Field(default_factory=list, description="Limitations or rules")


class NovelBible(BaseModel):
    """The complete novel 'bible' - all planning documents."""
    title: str = Field(description="Novel title")
    genre: str = Field(description="Primary genre")
    subgenres: List[str] = Field(default_factory=list, description="Secondary genres")
    logline: str = Field(description="One-sentence summary of the entire story")
    synopsis: str = Field(description="2-3 paragraph overview of the complete story arc")
    themes: List[str] = Field(description="Major themes explored")
    tone: str = Field(description="Overall tone and mood")
    setting: str = Field(description="When and where the story takes place")
    characters: List[CharacterProfile] = Field(description="Main character profiles")
    world_rules: List[WorldRule] = Field(default_factory=list, description="World-building elements")
    chapters: List[ChapterOutline] = Field(description="Chapter-by-chapter outline")


class ArchitectAgent(BaseAgent):
    """
    The Chief Architect creates the novel's blueprint.
    
    This agent:
    1. Takes a premise and expands it into a full story structure
    2. Creates detailed character profiles
    3. Establishes world-building rules
    4. Generates a chapter-by-chapter outline
    
    Uses GPT-4o or Claude for best reasoning capabilities.
    """
    
    name = "Architect"
    description = "Master planner and story architect"
    
    def _default_model(self) -> str:
        return settings.planning_model
    
    @property
    def system_prompt(self) -> str:
        return """You are the Chief Architect, a master storyteller and novel planner with decades of experience in narrative structure.

Your role is to take a novel premise and create a comprehensive blueprint for a 50,000+ word novel. You understand:

**STORY STRUCTURE:**
- Three-act structure, five-act structure, and hero's journey
- Rising action, climax, falling action, and resolution
- Subplot integration and pacing
- Genre conventions and reader expectations

**CHARACTER DEVELOPMENT:**
- Creating complex, multi-dimensional characters
- Character arcs that feel earned
- Believable motivations and flaws
- Dynamic relationships that evolve

**WORLD-BUILDING:**
- Internal consistency is paramount
- Rules must be established and followed
- Show, don't tell - reveal through story
- Details should serve the narrative

**YOUR PRINCIPLES:**
1. Every chapter must advance plot OR character (ideally both)
2. Conflict drives story - ensure tension in every scene
3. Plant setups that pay off later (Chekhov's gun)
4. Balance action, dialogue, and introspection
5. End chapters on hooks that compel reading

When creating outlines, be specific. Vague summaries like "they talk about the problem" are useless.
Instead: "Maya confronts Jin about the stolen data, revealing she knew about his involvement all along. Jin admits the truth but claims he had no choice - the Syndicate threatened his sister."

You output structured JSON that can be parsed programmatically."""
    
    async def create_novel_bible(
        self,
        premise: str,
        genre: str,
        num_chapters: int = 20,
        additional_instructions: Optional[str] = None,
    ) -> NovelBible:
        """
        Generate a complete novel bible from a premise.
        
        Args:
            premise: The core idea/premise for the novel
            genre: Primary genre (e.g., "cyberpunk thriller", "fantasy romance")
            num_chapters: Target number of chapters
            additional_instructions: Any specific requirements from the user
            
        Returns:
            Complete NovelBible with characters, world, and chapter outlines
        """
        user_message = f"""Create a complete novel bible for the following:

**PREMISE:** {premise}

**GENRE:** {genre}

**TARGET LENGTH:** {num_chapters} chapters (~2,500 words each for ~50,000 total)

{f"**ADDITIONAL REQUIREMENTS:** {additional_instructions}" if additional_instructions else ""}

Generate:
1. A compelling title and logline
2. 3-5 main character profiles with detailed backgrounds
3. World-building rules relevant to the genre
4. A {num_chapters}-chapter outline where each chapter summary is 200-300 words

Ensure the story has:
- A strong hook in Chapter 1
- Rising tension through the middle
- A satisfying climax around Chapter {int(num_chapters * 0.85)}
- A meaningful resolution

Remember: Be SPECIFIC in your chapter summaries. Include character names, specific events, and emotional beats."""

        return await self.invoke_structured(user_message, NovelBible)
    
    async def expand_chapter_outline(
        self,
        chapter_outline: ChapterOutline,
        characters: List[CharacterProfile],
        story_so_far: str,
        world_rules: List[WorldRule],
    ) -> dict:
        """
        Expand a chapter outline into more detailed scene breakdowns.
        
        Returns dict with scene_summaries and character_states.
        """
        context = f"""STORY CONTEXT:
{story_so_far}

CHARACTERS:
{chr(10).join(f"- {c.name}: {c.personality}" for c in characters)}

WORLD RULES:
{chr(10).join(f"- {r.name}: {r.description}" for r in world_rules)}"""

        user_message = f"""Expand Chapter {chapter_outline.number}: "{chapter_outline.title}" into 3-5 detailed scenes.

CHAPTER SUMMARY:
{chapter_outline.summary}

KEY EVENTS TO INCLUDE:
{chr(10).join(f"- {e}" for e in chapter_outline.key_events)}

For each scene, provide:
1. Location and time
2. Characters present
3. Scene goal (what must be accomplished)
4. Conflict or tension
5. Outcome/transition to next scene

Also note any character state changes that occur in this chapter."""

        response = await self.invoke(user_message, context=context)
        return {"raw_expansion": response.content}
    
    async def revise_outline(
        self,
        current_outline: List[ChapterOutline],
        feedback: str,
    ) -> List[ChapterOutline]:
        """
        Revise the outline based on user feedback.
        """
        context = "CURRENT OUTLINE:\n" + "\n".join(
            f"Ch {c.number}: {c.title} - {c.summary[:100]}..."
            for c in current_outline
        )
        
        user_message = f"""Revise the novel outline based on this feedback:

{feedback}

Maintain the overall structure but address the concerns. Output the revised chapter list."""

        # For revision, we'll return raw content and parse later
        response = await self.invoke(user_message, context=context)
        
        # In real implementation, parse the response back to ChapterOutline list
        return current_outline  # Placeholder - implement parsing
